### ISSUE TITLE
the See your stored items option doesn't work

### ISSUE THREAD

**Issue by giganlak** [giganlak/wood#180] opened 2022-07-23 02:51 UTC
![image](https://user-images.githubusercontent.com/79335163/180587888-866860ff-bdc6-48f9-aca3-5446351c6b3c.png)

**Comment by ConaII** [comment] 2022-07-23 03:04
Duplicate of #179

**Closed by ConaII** 2022-07-23 03:04 UTC
Labels: bug

**Comment by giganlak** [comment] 2022-07-23 03:12
que wea como que hice 2
